apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
      - name: fastapi-service
        image: 503147168047.dkr.ecr.ap-south-1.amazonaws.com/fastapi-service:latest  # Updated with ECR details
        ports:
        - containerPort: 8000
        imagePullPolicy: Always  # Ensures the latest image is pulled on deployment
